In [4]:
import pandas as pd

data = pd.read_excel('../data/raw/dataset_reduced.xlsx')
data

,Index,Name,Z,Period,Group,EN,CR,CM_type,CM_morph,MS2_morph,CP_morph,SSA,C,Cation,Anion,PW,CD,Cs,Ref,Ref_index
0,4,VS2,23,4,5,1.63,1.44,0,0,nanosheets,0,5.5,6.0,K,OH,0.5,1.0,152.0,10.1039/C5RA27155J,2
1,5,VS2,23,4,5,1.63,1.44,0,0,nanosheets,0,5.5,6.0,K,OH,0.5,2.0,145.0,10.1039/C5RA27155J,2
2,6,VS2,23,4,5,1.63,1.44,0,0,nanosheets,0,5.5,6.0,K,OH,0.5,5.0,136.0,10.1039/C5RA27155J,2
3,7,VS2,23,4,5,1.63,1.44,0,0,nanosheets,0,5.5,6.0,K,OH,0.5,10.0,120.0,10.1039/C5RA27155J,2
4,8,VS2,23,4,5,1.63,1.44,0,0,nanosheets,0,5.5,6.0,K,OH,0.5,15.0,90.0,10.1039/C5RA27155J,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,778,WS2/ACF,74,6,6,1.70,1.50,CNF,1D fibers,flower-like clusters,supported,10.8,1.0,K,OH,0.5,1.0,600.0,10.1039/C8TA01047A,80
578,779,WS2/ACF,74,6,6,1.70,1.50,CNF,1D fibers,flower-like clusters,supported,10.8,1.0,K,OH,0.5,2.0,527.0,10.1039/C8TA01047A,80
579,780,WS2/ACF,74,6,6,1.70,1.50,CNF,1D fibers,flower-like clusters,supported,10.8,1.0,K,OH,0.5,4.0,476.0,10.1039/C8TA01047A,80
580,781,WS2/ACF,74,6,6,1.70,1.50,CNF,1D fibers,flower-like clusters,supported,10.8,1.0,K,OH,0.5,8.0,391.0,10.1039/C8TA01047A,80
581,782,WS2/ACF,74,6,6,1.70,1.50,CNF,1D fibers,flower-like clusters,supported,10.8,1.0,K,OH,0.5,10.0,340.0,10.1039/C8TA01047A,80

In [5]:
# åˆ åŽ»Index, Nameåˆ—
data = data.drop(columns=['Index', 'Name', 'Ref', 'Ref_index'])
data

,Z,Period,Group,EN,CR,CM_type,CM_morph,MS2_morph,CP_morph,SSA,C,Cation,Anion,PW,CD,Cs
0,23,4,5,1.63,1.44,0,0,nanosheets,0,5.5,6.0,K,OH,0.5,1.0,152.0
1,23,4,5,1.63,1.44,0,0,nanosheets,0,5.5,6.0,K,OH,0.5,2.0,145.0
2,23,4,5,1.63,1.44,0,0,nanosheets,0,5.5,6.0,K,OH,0.5,5.0,136.0
3,23,4,5,1.63,1.44,0,0,nanosheets,0,5.5,6.0,K,OH,0.5,10.0,120.0
4,23,4,5,1.63,1.44,0,0,nanosheets,0,5.5,6.0,K,OH,0.5,15.0,90.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,74,6,6,1.70,1.50,CNF,1D fibers,flower-like clusters,supported,10.8,1.0,K,OH,0.5,1.0,600.0
578,74,6,6,1.70,1.50,CNF,1D fibers,flower-like clusters,supported,10.8,1.0,K,OH,0.5,2.0,527.0
579,74,6,6,1.70,1.50,CNF,1D fibers,flower-like clusters,supported,10.8,1.0,K,OH,0.5,4.0,476.0
580,74,6,6,1.70,1.50,CNF,1D fibers,flower-like clusters,supported,10.8,1.0,K,OH,0.5,8.0,391.0
581,74,6,6,1.70,1.50,CNF,1D fibers,flower-like clusters,supported,10.8,1.0,K,OH,0.5,10.0,340.0

In [6]:
# CM_type column
    # 0. NoCP
    # means pure MS2
    # 1. 1D CNF/CNT
    # includes CNF, CC, CNT and MWCNT.
    # 2. 2D G-based
    # includes Graphene, GO and RGO.
    # 3. 3D derived carbon-based
    # such carbon is obtained by carbonization of organic precursors.
    
replace_values = ['CNF', 'CC', 'CNT', 'MWCNT']
data['CM_type'] = data['CM_type'].replace(replace_values, '1')

replace_values = ['Graphene', 'GO', 'RGO']
data['CM_type'] = data['CM_type'].replace(replace_values, '2')

replace_values = ['derived carbon', 'derived carbon & CNT']
data['CM_type'] = data['CM_type'].replace(replace_values, '3')

# CM_morph column
    # 0. NoCP
    # means pure MS2
    # 1. 1D fibers & tubes.
    # includes 1D fibers and 1D tubes.
    # 2. 2D
    # includes 2D nanosheets (few layers, thick < 10 nm).
    # 3. 3D porous
    # includes 3D porous and 3D networks.
    # 4. 3D special
    # includes nanoparticles, nanospheres, rods, tubes and flower-like.
    
replace_values = ['1D fibers', '1D tubes']
data['CM_morph'] = data['CM_morph'].replace(replace_values, '1')

replace_values = ['2D nanosheets']
data['CM_morph'] = data['CM_morph'].replace(replace_values, '2')

replace_values = ['3D porous', '3D networks']
data['CM_morph'] = data['CM_morph'].replace(replace_values, '3')

replace_values = ['nanoparticles', 'nanospheres', 'rods', 'tubes', 'flower-like']
data['CM_morph'] = data['CM_morph'].replace(replace_values, '4')

# MS2_morph column
    # 0. bulk
    # no regular shape.
    # 1. nanosheets
    # flakeï¼Œnot few-layer sheet.
    # 2. flower-like clusters
    # aggregated from few-layer nanosheets.
    # 3. irregular nanoparticles
    # particles less than 1 Î¼m in size, but the size and dispersion degree are not uniform.
    # 4. nanoparticles
    # includes nanoparticles, octahedron, cubes, rods and spheres. 
    # the size and dispersion are uniform.
    # 5. hollow morph
    # includes hollow spheres, hollow rods, hollow cubes, hollow nanoparticles,
    # double shell spheres and yolk-shell spheres. 
    
replace_values = ['bulk']
data['MS2_morph'] = data['MS2_morph'].replace(replace_values, '0')

replace_values = ['nanosheets']
data['MS2_morph'] = data['MS2_morph'].replace(replace_values, '1')

replace_values = ['flower-like clusters']
data['MS2_morph'] = data['MS2_morph'].replace(replace_values, '2')

replace_values = ['irregular nanoparticles']
data['MS2_morph'] = data['MS2_morph'].replace(replace_values, '3')

replace_values = ['nanoparticles', 'octahedron', 'cubes', 'rods', 'spheres']
data['MS2_morph'] = data['MS2_morph'].replace(replace_values, '4')

replace_values = ['hollow spheres', 'hollow rods', 'hollow cubes', 'hollow nanoparticles', 'double shell spheres', 'yolk-shell spheres']
data['MS2_morph'] = data['MS2_morph'].replace(replace_values, '5')

# CP_morph column
    # 0. NoCP
    # 1. supported
    # 2. embedded
    # 3. coated
    # 4. interconnected
    
replace_values = ['supported']
data['CP_morph'] = data['CP_morph'].replace(replace_values, '1')

replace_values = ['embedded']
data['CP_morph'] = data['CP_morph'].replace(replace_values, '2')

replace_values = ['coated']
data['CP_morph'] = data['CP_morph'].replace(replace_values, '3')

replace_values = ['interconnected']
data['CP_morph'] = data['CP_morph'].replace(replace_values, '4')

data

,Z,Period,Group,EN,CR,CM_type,CM_morph,MS2_morph,CP_morph,SSA,C,Cation,Anion,PW,CD,Cs
0,23,4,5,1.63,1.44,0,0,1,0,5.5,6.0,K,OH,0.5,1.0,152.0
1,23,4,5,1.63,1.44,0,0,1,0,5.5,6.0,K,OH,0.5,2.0,145.0
2,23,4,5,1.63,1.44,0,0,1,0,5.5,6.0,K,OH,0.5,5.0,136.0
3,23,4,5,1.63,1.44,0,0,1,0,5.5,6.0,K,OH,0.5,10.0,120.0
4,23,4,5,1.63,1.44,0,0,1,0,5.5,6.0,K,OH,0.5,15.0,90.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,74,6,6,1.70,1.50,1,1,2,1,10.8,1.0,K,OH,0.5,1.0,600.0
578,74,6,6,1.70,1.50,1,1,2,1,10.8,1.0,K,OH,0.5,2.0,527.0
579,74,6,6,1.70,1.50,1,1,2,1,10.8,1.0,K,OH,0.5,4.0,476.0
580,74,6,6,1.70,1.50,1,1,2,1,10.8,1.0,K,OH,0.5,8.0,391.0
581,74,6,6,1.70,1.50,1,1,2,1,10.8,1.0,K,OH,0.5,10.0,340.0

In [7]:
data.dtypes

Z              int64
Period         int64
Group          int64
EN           float64
CR           float64
CM_type       object
CM_morph      object
MS2_morph     object
CP_morph      object
SSA          float64
C            float64
Cation        object
Anion         object
PW           float64
CD           float64
Cs           float64
dtype: object

In [8]:
data.to_csv('../data/processed/dataset_reduced.csv', index=False)